In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\MONIKA SHARMA\Downloads\archive (2).zip")

In [3]:
df

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,#Gadhvi (He thought he was Gandhi),2019,109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
1,#Yaaram,2019,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
2,...Aur Pyaar Ho Gaya,1997,147,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
3,...Yahaan,2005,142,"Drama, Romance, War",7.4,1086,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
4,?: A Question Mark,2012,82,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
...,...,...,...,...,...,...,...,...,...,...
5654,Zubaan,2015,115,Drama,6.1,408,Mozez Singh,Vicky Kaushal,Sarah Jane Dias,Raaghavv Chanana
5655,Zubeidaa,2001,153,"Biography, Drama, History",6.2,1496,Shyam Benegal,Karisma Kapoor,Rekha,Manoj Bajpayee
5656,Zulm Ki Zanjeer,1989,125,"Action, Crime, Drama",5.8,44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
5657,Zulmi,1999,129,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
5658,Zulm-O-Sitam,1998,130,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [4]:
df.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,#Gadhvi (He thought he was Gandhi),2019,109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
1,#Yaaram,2019,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
2,...Aur Pyaar Ho Gaya,1997,147,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
3,...Yahaan,2005,142,"Drama, Romance, War",7.4,1086,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
4,?: A Question Mark,2012,82,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia

In [5]:
df.tail()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
5654,Zubaan,2015,115,Drama,6.1,408,Mozez Singh,Vicky Kaushal,Sarah Jane Dias,Raaghavv Chanana
5655,Zubeidaa,2001,153,"Biography, Drama, History",6.2,1496,Shyam Benegal,Karisma Kapoor,Rekha,Manoj Bajpayee
5656,Zulm Ki Zanjeer,1989,125,"Action, Crime, Drama",5.8,44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
5657,Zulmi,1999,129,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
5658,Zulm-O-Sitam,1998,130,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [6]:
df.columns

Index(['Name', 'Year', 'Duration', 'Genre', 'Rating', 'Votes', 'Director',
       'Actor 1', 'Actor 2', 'Actor 3'],
      dtype='object')

In [20]:
df.shape   # shows rows and columns

(5659, 10)

In [21]:
df.dtypes

Name         object
Year          int64
Duration      int64
Genre        object
Rating      float64
Votes         int64
Director     object
Actor 1      object
Actor 2      object
Actor 3      object
dtype: object

In [22]:
df.describe()

              Year     Duration       Rating          Votes
count  5659.000000  5659.000000  5659.000000    5659.000000
mean   1996.247570   133.439124     5.898533    2697.649585
std      19.741839    25.319939     1.381165   13651.503584
min    1931.000000    21.000000     1.100000       5.000000
25%    1983.000000   119.000000     5.000000      30.000000
50%    2002.000000   135.000000     6.100000     131.000000
75%    2013.000000   150.000000     6.900000     922.500000
max    2021.000000   321.000000    10.000000  591417.000000

In [23]:
df.info()  #memmory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5659 entries, 0 to 5658
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5659 non-null   object
 1   Year      5659 non-null   int64
 2   Duration  5659 non-null   int64
 3   Genre     5659 non-null   object
 4   Rating    5659 non-null   float64
 5   Votes     5659 non-null   int64
 6   Director  5659 non-null   object
 7   Actor 1   5659 non-null   object
 8   Actor 2   5659 non-null   object
 9   Actor 3   5659 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 442.2+ KB

In [24]:
df[['Actor 1']]

              Actor 1
0        Rasika Dugal
1             Prateik
2          Bobby Deol
3     Jimmy Sheirgill
4           Yash Dave
...               ...
5654    Vicky Kaushal
5655   Karisma Kapoor
5656      Chiranjeevi
5657     Akshay Kumar
5658       Dharmendra

[5659 rows x 1 columns]

In [25]:
df[['Actor 1','Actor 2','Actor 3']]  #more than one column find

              Actor 1                 Actor 2           Actor 3
0        Rasika Dugal          Vivek Ghamande     Arvind Jangid
1             Prateik              Ishita Raj   Siddhant Kapoor
2          Bobby Deol  Aishwarya Rai Bachchan     Shammi Kapoor
3     Jimmy Sheirgill          Minissha Lamba    Yashpal Sharma
4           Yash Dave          Muntazir Ahmad      Kiran Bhatia
...               ...                     ...               ...
5654    Vicky Kaushal         Sarah Jane Dias  Raaghavv Chanana
5655   Karisma Kapoor                   Rekha    Manoj Bajpayee
5656      Chiranjeevi              Jayamalini       Rajinikanth
5657     Akshay Kumar          Twinkle Khanna       Aruna Irani
5658       Dharmendra              Jaya Prada       Arjun Sarja

[5659 rows x 3 columns]

In [26]:
df.isnull().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of        Name   Year  Duration  Genre  Rating  Votes  Director  Actor 1  \
0     False  False     False  False   False  False     False    False
1     False  False     False  False   False  False     False    False
2     False  False     False  False   False  False     False    False
3     False  False     False  False   False  False     False    False
4     False  False     False  False   False  False     False    False
...     ...    ...       ...    ...     ...    ...       ...      ...
5654  False  False     False  False   False  False     False    False
5655  False  False     False  False   False  False     False    False
5656  False  False     False  False   False  False     False    False
5657  False  False     False  False   False  False     False    False
5658  False  False     False  False   False  False     False    False

      Actor 2  Actor 3
0       False    False
1       False    False
2       False    False
3       False    False
4       False    False
...       ...      ...
5654    False    False
5655    False    False
5656    False    False
5657    False    False
5658    False    False

[5659 rows x 10 columns]>

In [28]:
df['Name'].unique()

array(['#Gadhvi (He thought he was Gandhi)', '#Yaaram',
       '...Aur Pyaar Ho Gaya', ..., 'Zulm Ki Zanjeer', 'Zulmi',
       'Zulm-O-Sitam'], dtype=object)

In [38]:
df[df['Director'] == 'Male']

Empty DataFrame
Columns: [Name, Year, Duration, Genre, Rating, Votes, Director, Actor 1, Actor 2, Actor 3]
Index: []

In [39]:
df.duplicated().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of 0       False
1       False
2       False
3       False
4       False
        ...
5654    False
5655    False
5656    False
5657    False
5658    False
Length: 5659, dtype: bool>

In [40]:
df['Rating'].max()

10.0

In [41]:
df['Rating'].min()

1.1

In [42]:
df.duplicated().shape

(5659,)

In [44]:
df.drop_duplicates().shape

(5659, 10)